/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.performia;

import java.awt.CardLayout;
import javax.swing.Box;

/**
 *
 * @author faizd
 */
public class MainFrame_GUI_Manajer extends javax.swing.JFrame {
    private int indexManajer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame_GUI_Manajer.class.getName());
    private final CardLayout cardLayout;
    private PanelDashboard_GUI_Manajer dashboard;
    private PanelReviewAssignment_GUI reviewAssignment;
    
    /**
     * Creates new form MainFrame_GUI_Manajer
     */
    public MainFrame_GUI_Manajer(int indexManajer) {
        initComponents();
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(menuLogout);
        this.indexManajer = indexManajer;
        setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        panelMenu.setLayout(cardLayout);

        dashboard = new PanelDashboard_GUI_Manajer(indexManajer);
        PanelCreateAssignment_GUI createAssignment = new PanelCreateAssignment_GUI();
        reviewAssignment = new PanelReviewAssignment_GUI();
        PanelRanking_GUI ranking = new PanelRanking_GUI();

        panelMenu.add(dashboard, "Dashboard");
        panelMenu.add(createAssignment, "Create Assignment");
        panelMenu.add(reviewAssignment, "Review Assignment");
        panelMenu.add(ranking, "Ranking");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        menuCreateAssignment = new javax.swing.JMenu();
        menuReviewAssignment = new javax.swing.JMenu();
        menuRanking = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelMenuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        menuDashboard.setText("Dashboard");
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
        });
        menuBar.add(menuDashboard);

        menuCreateAssignment.setText("Create Assignment");
        menuCreateAssignment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCreateAssignmentMouseClicked(evt);
            }
        });
        menuBar.add(menuCreateAssignment);

        menuReviewAssignment.setText("Review Assignment");
        menuReviewAssignment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReviewAssignmentMouseClicked(evt);
            }
        });
        menuBar.add(menuReviewAssignment);

        menuRanking.setText("Ranking");
        menuRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRankingMouseClicked(evt);
            }
        });
        menuBar.add(menuRanking);

        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        dashboard.refreshDaftarReviewTugas();
        cardLayout.show(panelMenu, "Dashboard");
    }//GEN-LAST:event_menuDashboardMouseClicked

    private void menuCreateAssignmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCreateAssignmentMouseClicked
        cardLayout.show(panelMenu, "Create Assignment");
    }//GEN-LAST:event_menuCreateAssignmentMouseClicked

    private void menuReviewAssignmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReviewAssignmentMouseClicked
        reviewAssignment.refreshTugas();
        
        cardLayout.show(panelMenu, "Review Assignment");
    }//GEN-LAST:event_menuReviewAssignmentMouseClicked

    private void menuRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRankingMouseClicked
        cardLayout.show(panelMenu, "Ranking");
    }//GEN-LAST:event_menuRankingMouseClicked

    private void panelMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelMenuAncestorAdded

    }//GEN-LAST:event_panelMenuAncestorAdded

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        Login login = new Login();
        
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MainFrame_GUI_Manajer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCreateAssignment;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuRanking;
    private javax.swing.JMenu menuReviewAssignment;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
