/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.performia;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faizd
 */
public class PanelReviewAssignment_GUI extends javax.swing.JPanel {
    private DefaultTableModel model;
    /**
     * Creates new form PanelReviewAssignment_GUI
     */
    private ArrayList<Integer> listIndexTugas = new ArrayList<>();
    public PanelReviewAssignment_GUI() {
        initComponents();
        refreshTugas();
    }
    
    public void refreshTugas(){
        Performia p = new Performia();
        model = (DefaultTableModel) tabelDaftarTugas.getModel();
        model.setRowCount(0);
        listIndexTugas.clear();
        for(int i = 0; i < p.getJumlahTugas();i++){
            if(p.getStatusTugas(i).equalsIgnoreCase("Waiting for Review")){
                model.addRow(new Object[]{p.getJudulTugas(i), p.getTanggalDikumpulkanTugas(i), p.getStatusTugas(i)});
                listIndexTugas.add(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarTugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bReview = new javax.swing.JButton();

        tabelDaftarTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tugas", "Tanggal Dikumpulkan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDaftarTugas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Tugas");

        bReview.setText("Review");
        bReview.addActionListener(this::bReviewActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bReview, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bReview)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReviewActionPerformed
        Performia p = new Performia();
        int pilihTugas = tabelDaftarTugas.getSelectedRow();
        if (pilihTugas == -1) {
            JOptionPane.showMessageDialog(this,"Pilih tugas terlebih dahulu!");
        } else {
            String feedback = JOptionPane.showInputDialog(this,"Berikan feedback:");
            if (feedback != null && !feedback.isEmpty()) {
                int indexTugas = listIndexTugas.get(pilihTugas);
                p.setStatusTugas(indexTugas, "Done");
                refreshTugas();
                JOptionPane.showMessageDialog(this, "Tugas berhasil direview!");
            }
        }
    }//GEN-LAST:event_bReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDaftarTugas;
    // End of variables declaration//GEN-END:variables
}
