/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.performia;

/**
 *
 * @author ARTHES
 */
public class PanelRiwayat_GUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelRiwayat_GUI
     */
    public PanelRiwayat_GUI() {
        initComponents();
        String[] namaKolom = {"Tanggal", "Nama Tugas", "Skor XP"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(namaKolom, 0);

        model.addRow(new Object[]{"12 Jun 2026", "Maintenance website", 150});
        model.addRow(new Object[]{"10 Jun 2026", "Fixing bug database", 200});
        model.addRow(new Object[]{"05 Jun 2026", "Update UI Dashboard", 100});

        TabelRiwayat.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RiwayatPenugasan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelRiwayat = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 51, 102));

        RiwayatPenugasan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RiwayatPenugasan.setText("Riwayat Penugasan");

        TabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Tugas", "Skor XP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelRiwayat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RiwayatPenugasan)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RiwayatPenugasan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RiwayatPenugasan;
    private javax.swing.JTable TabelRiwayat;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
