/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.performia;
import java.awt.Color;
import java.time.LocalDate;
//import java.util.concurrent.ThreadLocalRandom;
/**
 *
 * @author ARTHES
 */

public class PanelPerformance_GUI extends javax.swing.JPanel {
    Performa pfm = new Performa();
    private int previousCompletedAssignments = -1;
    private int akunAktif;
    /**
     * Creates new form PanelPerformance_GUI
     */
    public PanelPerformance_GUI(int akunAktif) {
        initComponents();
        this.akunAktif = akunAktif;
        reloadPerformanceData();
    }

    public PanelPerformance_GUI(Performa performanceData) {
        initComponents();
        if (performanceData != null) {
            previousCompletedAssignments = performanceData.getTugasSelesai();
            updateData(
                    performanceData.getTugasSelesai(),
                    performanceData.getTugasProgres(),
                    performanceData.getTotalTugas(),
                    Math.round(performanceData.getOnTimeRate()),
                    Math.max(performanceData.getTotalTugas() - Math.round(performanceData.getOnTimeRate()), 0),
                    performanceData.getTotalTugas(),
                    performanceData.getTotalXP()
            );
        } else {
            reloadPerformanceData();
        }
    }

    public void refreshPerformanceData() {
        reloadPerformanceData();
    }

    private void reloadPerformanceData() {
        Performia p = new Performia();
        Karyawan k = Performia.listKaryawan.get(akunAktif);
        int totalTugas = k.getTotalTugas();
        int tugasSelesai = 0;
        int tugasOnTime = 0;
        int tugasOverdue = 0;
        LocalDate hariIni = LocalDate.now();

        for (int i = 0; i < totalTugas; i++) {
            Tugas t = k.getListTugas(i);
            boolean selesai = t.getStatus().equalsIgnoreCase("Done");
            boolean overdue = t.getTanggalBatas().isBefore(hariIni);

            if (selesai) {
                tugasSelesai++;
                tugasOnTime++;
            }

            if (overdue) {
                tugasOverdue++;
            }
        }

        int tugasProgres = Math.max(totalTugas - tugasSelesai, 0);
        int totalPerformance = totalTugas;

        if (previousCompletedAssignments >= 0 && tugasSelesai > previousCompletedAssignments && !Performia.listKaryawan.isEmpty()) {
            int newlyCompletedAssignments = tugasSelesai - previousCompletedAssignments;
            int totalBonusXP = 0;

            for (int i = 0; i < newlyCompletedAssignments; i++) {
//                totalBonusXP += generateRandomXpBonus();
//                totalBonusXP += pfm.generateXP();
                Tugas t = k.getListTugas(i);
                int XP = t.getSkorXP();
                
//                totalBonusXP += Performa.getRecentTaskXP();
                totalBonusXP += XP;
            }

//            Performia.listKaryawan.get(0).tambahXP(totalBonusXP);
        }

        previousCompletedAssignments = tugasSelesai;

        int totalXP = 0;

        if (!Performia.listKaryawan.isEmpty()) {
            totalXP = k.getTotalXP();
        }

        updateData(
                tugasSelesai,
                tugasProgres,
                totalTugas,
                tugasOnTime,
                tugasOverdue,
                totalPerformance,
                totalXP
        );
    }

//    private int generateRandomXpBonus() {
//        return ThreadLocalRandom.current().nextInt(1, 21) * 5;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Assignment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pbSelesai = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pbDalamProgres = new javax.swing.JProgressBar();
        lblAngkaDP = new javax.swing.JLabel();
        lblAngkaSelesai = new javax.swing.JLabel();
        jP_Performance = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pbOnTime = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        pbOverdue = new javax.swing.JProgressBar();
        lblAngkaOT = new javax.swing.JLabel();
        lblAngkaOD = new javax.swing.JLabel();
        jP_HEADER = new javax.swing.JPanel();
        L_Performance = new javax.swing.JLabel();
        jP_Skor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblXP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jP_Assignment.setBackground(new java.awt.Color(255, 255, 255));
        jP_Assignment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assignment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jP_Assignment.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Selesai");

        pbSelesai.setBackground(new java.awt.Color(204, 204, 204));
        pbSelesai.setForeground(new java.awt.Color(0, 153, 0));
        pbSelesai.setValue(50);

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Dalam Progres");

        pbDalamProgres.setBackground(new java.awt.Color(204, 204, 204));
        pbDalamProgres.setValue(50);

        lblAngkaDP.setForeground(new java.awt.Color(51, 51, 51));
        lblAngkaDP.setText("[] / []");

        lblAngkaSelesai.setForeground(new java.awt.Color(51, 51, 51));
        lblAngkaSelesai.setText("[] / []");

        javax.swing.GroupLayout jP_AssignmentLayout = new javax.swing.GroupLayout(jP_Assignment);
        jP_Assignment.setLayout(jP_AssignmentLayout);
        jP_AssignmentLayout.setHorizontalGroup(
            jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AssignmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbDalamProgres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAngkaDP)
                    .addComponent(lblAngkaSelesai))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jP_AssignmentLayout.setVerticalGroup(
            jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AssignmentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pbSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAngkaSelesai))
                .addGap(25, 25, 25)
                .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pbDalamProgres, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAngkaDP))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jP_Performance.setBackground(new java.awt.Color(255, 255, 255));
        jP_Performance.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Performance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("On-Time");

        pbOnTime.setBackground(new java.awt.Color(204, 204, 204));
        pbOnTime.setForeground(new java.awt.Color(51, 153, 0));
        pbOnTime.setValue(80);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Overdue");

        pbOverdue.setBackground(new java.awt.Color(204, 204, 204));
        pbOverdue.setForeground(new java.awt.Color(51, 153, 0));
        pbOverdue.setValue(80);

        lblAngkaOT.setText("[] / []");

        lblAngkaOD.setText("[] / []");

        javax.swing.GroupLayout jP_PerformanceLayout = new javax.swing.GroupLayout(jP_Performance);
        jP_Performance.setLayout(jP_PerformanceLayout);
        jP_PerformanceLayout.setHorizontalGroup(
            jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PerformanceLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_PerformanceLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbOnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_PerformanceLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbOverdue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAngkaOT)
                    .addComponent(lblAngkaOD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_PerformanceLayout.setVerticalGroup(
            jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PerformanceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(pbOnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAngkaOT))
                .addGap(18, 18, 18)
                .addGroup(jP_PerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(pbOverdue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAngkaOD))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jP_HEADER.setBackground(new java.awt.Color(204, 204, 204));

        L_Performance.setBackground(new java.awt.Color(255, 255, 255));
        L_Performance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        L_Performance.setForeground(new java.awt.Color(51, 51, 51));
        L_Performance.setText("Performance");

        javax.swing.GroupLayout jP_HEADERLayout = new javax.swing.GroupLayout(jP_HEADER);
        jP_HEADER.setLayout(jP_HEADERLayout);
        jP_HEADERLayout.setHorizontalGroup(
            jP_HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_HEADERLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(L_Performance)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_HEADERLayout.setVerticalGroup(
            jP_HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_HEADERLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(L_Performance)
                .addGap(15, 15, 15))
        );

        jP_Skor.setBackground(new java.awt.Color(255, 255, 255));
        jP_Skor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jP_Skor.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total XP Anda:");

        lblXP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblXP.setForeground(new java.awt.Color(51, 51, 51));
        lblXP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXP.setText("[] XP");

        javax.swing.GroupLayout jP_SkorLayout = new javax.swing.GroupLayout(jP_Skor);
        jP_Skor.setLayout(jP_SkorLayout);
        jP_SkorLayout.setHorizontalGroup(
            jP_SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );
        jP_SkorLayout.setVerticalGroup(
            jP_SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SkorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_Performance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Assignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jP_Skor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_Assignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jP_Performance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_Skor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Performance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jP_Assignment;
    private javax.swing.JPanel jP_HEADER;
    private javax.swing.JPanel jP_Performance;
    private javax.swing.JPanel jP_Skor;
    private javax.swing.JLabel lblAngkaDP;
    private javax.swing.JLabel lblAngkaOD;
    private javax.swing.JLabel lblAngkaOT;
    private javax.swing.JLabel lblAngkaSelesai;
    private javax.swing.JLabel lblXP;
    private javax.swing.JProgressBar pbDalamProgres;
    private javax.swing.JProgressBar pbOnTime;
    private javax.swing.JProgressBar pbOverdue;
    private javax.swing.JProgressBar pbSelesai;
    // End of variables declaration//GEN-END:variables
    
    private void updateData(int tugasSelesai, int tugasDP, int totalAssignment,
                            int tugasOnTime, int tugasOverdue, int totalPerformance, int totalXP) {
        pbSelesai.setMaximum(totalAssignment);
        pbSelesai.setValue(tugasSelesai);
        lblAngkaSelesai.setText(tugasSelesai + " / " + totalAssignment);

        pbDalamProgres.setMaximum(totalAssignment);
        pbDalamProgres.setValue(tugasDP);
        lblAngkaDP.setText(tugasDP + " / " + totalAssignment);

        pbOnTime.setMaximum(totalPerformance);
        pbOnTime.setValue(tugasOnTime);
        lblAngkaOT.setText(tugasOnTime + " / " + totalPerformance);

        pbOverdue.setMaximum(totalPerformance);
        pbOverdue.setValue(tugasOverdue);
        lblAngkaOD.setText(tugasOverdue + " / " + totalPerformance);

        lblXP.setText(totalXP + " XP");

        int skorPerforma;
        if(totalPerformance == 0){
            skorPerforma = 0;
        } else {
            skorPerforma = Math.round((tugasOnTime * 100.0f) / totalPerformance);
        }
        
        if (skorPerforma >= 80) {
            pbOnTime.setForeground(new Color(50, 200, 50));
        } else if (skorPerforma >= 60) {
            pbOnTime.setForeground(Color.ORANGE);
        } else {
            pbOnTime.setForeground(new Color(220, 50, 50));
        }

        if (tugasOverdue > 0) {
            pbOverdue.setForeground(new Color(220, 50, 50));
        } else {
            pbOverdue.setForeground(new Color(50, 200, 50));
        }

        this.revalidate();
        this.repaint();
    }
    
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(() -> {
//            JFrame frame = new JFrame("Preview Panel Performance");
//            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            frame.setSize(600, 400);
//            
//            // Menambahkan panel yang baru dibuat ke dalam frame
//            frame.add(new PanelPerformance_GUI());
//            
//            frame.setLocationRelativeTo(null);
//            frame.setVisible(true);
//        });
//    }
}
