/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.performia;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author ARTHES
 */
public class PanelRanking_GUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelRanking_GUI
     */
    public PanelRanking_GUI() {
        initComponents();
        
        // JALAN PERTAMA KALI: Muat data saat objek pertama kali dibuat
        loadRankingData();
        
        // JALAN SETIAP DIKLIKS/DIBUKA: Trigger otomatis setiap kali panel ini ditampilkan kembali di layar
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                loadRankingData();
            }
        });
    }

    /**
     * Method untuk mengambil, mengurutkan, dan menampilkan data ke JTable
     */
    public void loadRankingData() {
        // Tarik model tabelnya
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jtRanking.getModel();
        
        // Bersihkan seluruh baris lama agar data tidak menumpuk/double saat di-refresh
        model.setRowCount(0);

        // 1. Salin data dari listKaryawan yang ada di memori Performia.java
        ArrayList<Karyawan> sortedKaryawan = new ArrayList<>(Performia.listKaryawan);

        // 2. Urutkan data berdasarkan TotalXP secara Descending (tertinggi ke terendah)
        Collections.sort(sortedKaryawan, new Comparator<Karyawan>() {
            public int compare(Karyawan k1, Karyawan k2) {
                return Integer.compare(k2.getTotalXP(), k1.getTotalXP());
            }
        });

        // 3. Masukkan data hasil urutan terbaru ke dalam JTable
        for (int i = 0; i < sortedKaryawan.size(); i++) {
            Karyawan k = sortedKaryawan.get(i);
            
            // Tentukan reward berdasarkan posisi ranking terbaru
            Reward reward;
            if (i == 0) {
                reward = new Reward("R01", "Bonus Rp 1.000.000");
            } else if (i == 1) {
                reward = new Reward("R02", "Bonus Rp 500.000");
            } else if (i == 2){
                reward = new Reward("R03", "Bonus Rp 300.000");
            } else {
                reward = new Reward("R00", "Tidak ada bonus");
            }
            
            // Bungkus ke objek Ranking
            Ranking rank = new Ranking("Juni 2026", k.getNama(), k.getTotalXP(), reward);
            
            // Masukkan baris baru ke JTable
            model.addRow(new Object[]{ 
                String.valueOf(i + 1), // Nomor ranking otomatis terupdate sesuai posisi urutan
                rank.getNamaKaryawan(), 
                rank.getPeriode(), 
                rank.getSkorAkhir() + " XP", 
                rank.getRewardYangDidapat().getNamaReward() 
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRanking = new javax.swing.JTable();

        jLabel2.setText("Ranking");

        jtRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Nama", "Periode", "Skor", "Reward"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtRanking);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRanking;
    // End of variables declaration//GEN-END:variables
}
