/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.performia;

/**
 *
 * @author ARTHES
 */
public class PanelRiwayat_GUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelRiwayat_GUI
     */
    private int akunAktif;
    public PanelRiwayat_GUI(int akunAktif) {
        initComponents();
        this.akunAktif = akunAktif;
        muatUlangRiwayat();
    }
public void muatUlangRiwayat() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) TabelRiwayat.getModel();
    model.setRowCount(0); // Kosongin dulu biar gak numpuk
    
    Karyawan k = Performia.listKaryawan.get(akunAktif);
    for(int i = 0; i < k.getTotalRiwayat(); i++){
        RiwayatPenugasan rp = k.getListRiwayatPenugasan(i);
        model.addRow(new Object[] {rp.getTanggal(), rp.getNamaTugas(), rp.getSkorXP() + " XP"});
    }
    
//    for (RiwayatPenugasan r : Performia.listRiwayat) {
//        model.addRow(new Object[]{
//            r.getTanggal(),
//            r.getNamaTugas(),
//            r.getSkorXP() + " XP"
//        });
//    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelRiwayat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        RiwayatPenugasan = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        TabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Tugas", "Skor XP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelRiwayat);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        RiwayatPenugasan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RiwayatPenugasan.setForeground(new java.awt.Color(51, 51, 51));
        RiwayatPenugasan.setText("Riwayat Penugasan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(RiwayatPenugasan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(RiwayatPenugasan)
                .addGap(18, 18, 18))
        );

        Refresh.setText("Refresh");
        Refresh.addActionListener(this::RefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Refresh)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Refresh)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
       muatUlangRiwayat();
    }//GEN-LAST:event_RefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel RiwayatPenugasan;
    private javax.swing.JTable TabelRiwayat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
